services:

  bash:
    image: civisdk/shell
    build: 
      context: docker/sdk
      args:
        LOGIN_UID: ${LOGIN_UID}
        LOGIN_GID: ${LOGIN_GID}
        FROM_IMAGE: civisdk/php
    volumes:
      - ./volumes/home:/home/cividev
      - htdocs:/var/www/html
      - ./app:/home/cividev/app
      - ./conf:/home/cividev/conf