services:
  php7-apache:
    build:
      args:
        PHP_CONFIGURE_GD_OPTS: --with-jpeg
        PHP_VERSION: '7.4'
      context: ./docker/php-apache
    environment:
      GD_OPTS_POST_74: --with-jpeg
      HOST_IP: 192.168.10.1
      LOGIN_GID: '1000'
      LOGIN_UID: '1000'
      XDEBUG_CONFIG: client_host=192.168.10.1
    extra_hosts:
      host.docker.internal: host-gateway
    image: nadcp/php7-apache
    ports:
    - published: 8080
      target: 8080
    - published: 9000
      target: 9000
    - published: 9003
      target: 9003
    volumes:
    - ./volume/htdocs:/var/www/html:rw
  php8-apache:
    build:
      args:
        PHP_CONFIGURE_GD_OPTS: --with-jpeg
        PHP_VERSION: '8.0'
      context: ./docker/php-apache
    environment:
      GD_OPTS_POST_74: --with-jpeg
      HOST_IP: 192.168.10.1
      LOGIN_GID: '1000'
      LOGIN_UID: '1000'
      XDEBUG_CONFIG: client_host=192.168.10.1
    extra_hosts:
      host.docker.internal: host-gateway
    image: nadcp/php8-apache
    ports:
    - published: 8080
      target: 8080
    - published: 9000
      target: 9000
    - published: 9003
      target: 9003
    volumes:
    - ./volume/htdocs:/var/www/html:rw
  sdk-php7:
    build:
      args:
        FROM_IMAGE: nadcp/php7-apache:latest
        LOGIN_GID: '1000'
        LOGIN_UID: '1000'
      context: ./docker/sdk
    image: nadcp/sdk-php7
  sdk-php8:
    build:
      args:
        FROM_IMAGE: nadcp/php8-apache:latest
        LOGIN_GID: '1000'
        LOGIN_UID: '1000'
      context: ./docker/sdk
    image: nadcp/sdk-php8
version: '3.9'

