services:
  mailhog:
    image: mailhog/mailhog:latest
    ports:
    - published: 1025
      target: 1025
    - published: 8025
      target: 8025
  mysql57:
    command: --skip-log-bin
    environment:
    - MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE
    - MYSQL_USER
    - MYSQL_PASSWORD    
    expose:
    - '3306'
    image: mysql:5.7
    volumes:
    - mysql57_var_lib:/var/lib/mysql:rw
  php7-apache:
    environment:
      GD_OPTS_POST_74: --with-jpeg
      HOST_IP: 192.168.10.1
      LOGIN_GID: '1000'
      LOGIN_UID: '1000'
      XDEBUG_CONFIG: client_host=192.168.10.1
    extra_hosts:
      host.docker.internal: host-gateway
    image: caracolazul/nadcp-apache:php7
    ports:
    - published: 8080
      target: 8080
    - published: 9000
      target: 9000
    - published: 9003
      target: 9003
    volumes:
    - ./volume/htdocs:/var/www/html:rw
  shell:
    command: bash
    entrypoint: sh -c
    extra_hosts:
      host.docker.internal: host-gateway
    image: caracolazul/nadcp-sdk:php7
    tty: true
    volumes:
    - ./volume/home:/home/cividev:rw
    - ./volume/arch:/var/arch:rw
    - ./volume/src:/var/src:rw
    - ./volume/htdocs:/var/www/html:rw
version: '3.9'
volumes:
  mysql57_var_lib: {}

