services:

  mysql8: 
    image: mysql:8
    expose:
      - 3306
    volumes: 
      - var_mysql8:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD