services:

  mysql56: 
    image: mysql:5.6
    expose:
      - 3306
    volumes: 
      - var_mysql56:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD