services:

  mysql8: 
    image: mysql:8
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - web_db_var_lib:/var/lib/mysql
