services:

  mysql:
    image: mysql:5.7
    expose:
      - 3306
    volumes: 
      - var_mysql57:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD