services:

  php:
    image: civisdk/php:7.0
    build:
      context: docker/php
      args:
        PHP_VERSION: 7.0
        PHP_CONFIGURE_GD_OPTS: ${GD_OPTS_PRE_74}
        # PHP_CONFIGURE_GD_OPTS: ${GD_OPTS_POST_74}
        LOGIN_UID: ${LOGIN_UID:-1000}
    ports:
      - 8080:8080
      - 9003:9003
      - 9000:9000
    volumes:
      - volumes/htdocs:/var/www/html
      - ./docker/php/php.sdk.ini:/usr/local/etc/php/conf.d/sdk.ini:ro
    environment:
      - XDEBUG_CONFIG=client_host=${HOST_IP} # https://xdebug.org/docs/all_settings
      - APACHE_RUN_USER=${USER_NAME:-docker-user}
    links:
      - mysql57 # TODO RM