services:

  php8-apache:
    image: nadcp/php8-apache
    build:
      context: service/php8-apache
      args:
        PHP_VERSION: 8.0
        # PHP_CONFIGURE_GD_OPTS: ${GD_OPTS_PRE_74}
        PHP_CONFIGURE_GD_OPTS: ${GD_OPTS_POST_74}
        LOGIN_UID: ${LOGIN_UID:-1000}
    environment:
      - XDEBUG_CONFIG=client_host=${HOST_IP} # https://xdebug.org/docs/all_settings
      - APACHE_RUN_USER=${USER_NAME:-docker-user}
    ports:
      - 8080:8080
      - 9003:9003
      - 9000:9000
    volumes:
      - web_htdocs:/var/www/html
