services:

  mariadb:
    image: mariadb:10.7
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    command: --skip-log-bin
    volumes:
      - mariadb_var_lib:/var/lib/mysql

volumes:
  mariadb_var_lib: