services:

  mysql8-cli: 
    image: mysql:8
    command: 
      - "/usr/bin/mysql"
      - "-h${MYSQL_HOST}"
      - "-u${MYSQL_USER}"
      - "-p${MYSQL_PASSWORD}"
    environment:
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./volume/src:/tmp/src
    extra_hosts:
      - "host.docker.internal:host-gateway"
