services:

  mysql57:
    image: mysql:5.7
    expose:
    - 3306
    environment:
    - MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE
    - MYSQL_USER
    - MYSQL_PASSWORD
    command: --skip-log-bin
    volumes:
    - mysql57_var_lib:/var/lib/mysql

volumes:
  mysql57_var_lib:
