services:

  mysql8: 
    image: mariadb:10.7
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    env_file: 
      - docker/mysql8.env
    command: --skip-log-bin
    volumes:
      - web_db_var_lib:/var/lib/mysql

volumes:
  web_db_var_lib: