services:

  php7-apache:
    image: nadcp/php7-apache
    build:
      context: docker/php-apache
      args:
        PHP_VERSION: 7.4
        # PHP_CONFIGURE_GD_OPTS: ${GD_OPTS_PRE_74}
        PHP_CONFIGURE_GD_OPTS: ${GD_OPTS_POST_74}
        # LOGIN_UID: ${LOGIN_UID:-1000}
    environment:
      - XDEBUG_CONFIG=client_host=${HOST_IP} # https://xdebug.org/docs/all_settings
      # - APACHE_RUN_USER=${USER_NAME:-docker-user}
    ports:
      - 8080:8080
      - 9003:9003
      - 9000:9000
    volumes:
      - web_htdocs:/var/www/html
    env_file:
      - docker/php7-apache.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
volumes:
  web_htdocs: