services:

  sdk-php7:
    image: caracolazul/nadcp-sdk:php7
    build:
      context: docker/sdk
      args:
        LOGIN_UID: ${LOGIN_UID:-1000}
        LOGIN_GID: ${LOGIN_GID:-1000}
        FROM_IMAGE: caracolazul/nadcp-apache:php7