services:

  sdk:
    image: nadcp/sdk
    build:
      context: docker/sdk
      args:
        LOGIN_UID: ${LOGIN_UID:-1000}
        LOGIN_GID: ${LOGIN_GID:-1000}
        FROM_IMAGE: nadcp/php8-apache:latest