services:

  shell:
    image: nadcp-sdk:php7
    tty: true
    entrypoint: sh -c
    command: bash
    volumes:
      - ./volume/htdocs:/var/www/html
      - ./volume/home:/home/cividev
      - ./volume/arch:/var/arch
      - ./volume/src:/var/src
    extra_hosts:
      - "host.docker.internal:host-gateway"
